CREATE TABLE Role (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	userId INT
);

CREATE TABLE User (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(200) NOT NULL,
	password VARCHAR(100) NOT NULL,
	passwordConfirm VARCHAR(100) NOT NULL,
	roleId INT
);

ALTER TABLE Role
ADD CONSTRAINT FK_RolesUser
FOREIGN KEY (userId) REFERENCES User(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE User
ADD CONSTRAINT FK_UsersRole
FOREIGN KEY (roleId) REFERENCES Role(id)
ON UPDATE CASCADE
ON DELETE CASCADE;